name: text_transformation_animation_widget
description: A text transformation animation.
version: 0.0.1
author: dhshah
homepage: https://github.com/dhshah/FlutterTextTransformationAnimationWidget

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
